<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Activities', 'doctrine');

/**
 * BaseActivities
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $activity_id
 * @property integer $book_id
 * @property integer $activity_type_id
 * @property string $name
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property ActivityType $ActivityType
 * @property Book $Book
 * @property Doctrine_Collection $AssessmentResultBoolean
 * @property Doctrine_Collection $AssessmentResultFloat
 * @property Doctrine_Collection $AssessmentResultInteger
 * @property Doctrine_Collection $AssessmentResultVarchar
 * @property Doctrine_Collection $AssessmentResultsWordHunt
 * 
 * @method integer             getActivityId()                Returns the current record's "activity_id" value
 * @method integer             getBookId()                    Returns the current record's "book_id" value
 * @method integer             getActivityTypeId()            Returns the current record's "activity_type_id" value
 * @method string              getName()                      Returns the current record's "name" value
 * @method timestamp           getCreatedAt()                 Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()                 Returns the current record's "updated_at" value
 * @method ActivityType        getActivityType()              Returns the current record's "ActivityType" value
 * @method Book                getBook()                      Returns the current record's "Book" value
 * @method Doctrine_Collection getAssessmentResultBoolean()   Returns the current record's "AssessmentResultBoolean" collection
 * @method Doctrine_Collection getAssessmentResultFloat()     Returns the current record's "AssessmentResultFloat" collection
 * @method Doctrine_Collection getAssessmentResultInteger()   Returns the current record's "AssessmentResultInteger" collection
 * @method Doctrine_Collection getAssessmentResultVarchar()   Returns the current record's "AssessmentResultVarchar" collection
 * @method Doctrine_Collection getAssessmentResultsWordHunt() Returns the current record's "AssessmentResultsWordHunt" collection
 * @method Activities          setActivityId()                Sets the current record's "activity_id" value
 * @method Activities          setBookId()                    Sets the current record's "book_id" value
 * @method Activities          setActivityTypeId()            Sets the current record's "activity_type_id" value
 * @method Activities          setName()                      Sets the current record's "name" value
 * @method Activities          setCreatedAt()                 Sets the current record's "created_at" value
 * @method Activities          setUpdatedAt()                 Sets the current record's "updated_at" value
 * @method Activities          setActivityType()              Sets the current record's "ActivityType" value
 * @method Activities          setBook()                      Sets the current record's "Book" value
 * @method Activities          setAssessmentResultBoolean()   Sets the current record's "AssessmentResultBoolean" collection
 * @method Activities          setAssessmentResultFloat()     Sets the current record's "AssessmentResultFloat" collection
 * @method Activities          setAssessmentResultInteger()   Sets the current record's "AssessmentResultInteger" collection
 * @method Activities          setAssessmentResultVarchar()   Sets the current record's "AssessmentResultVarchar" collection
 * @method Activities          setAssessmentResultsWordHunt() Sets the current record's "AssessmentResultsWordHunt" collection
 * 
 * @package    ruckus_dev
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActivities extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('activities');
        $this->hasColumn('activity_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('book_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('activity_type_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ActivityType', array(
             'local' => 'activity_type_id',
             'foreign' => 'activity_type_id'));

        $this->hasOne('Book', array(
             'local' => 'book_id',
             'foreign' => 'book_id'));

        $this->hasMany('AssessmentResultBoolean', array(
             'local' => 'activity_id',
             'foreign' => 'activity_id'));

        $this->hasMany('AssessmentResultFloat', array(
             'local' => 'activity_id',
             'foreign' => 'activity_id'));

        $this->hasMany('AssessmentResultInteger', array(
             'local' => 'activity_id',
             'foreign' => 'activity_id'));

        $this->hasMany('AssessmentResultVarchar', array(
             'local' => 'activity_id',
             'foreign' => 'activity_id'));

        $this->hasMany('AssessmentResultsWordHunt', array(
             'local' => 'activity_id',
             'foreign' => 'activity_id'));
    }
}