<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Achievements', 'doctrine');

/**
 * BaseAchievements
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $achievement_id
 * @property string $name
 * @property string $ach_description
 * @property string $ach_image
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $StudentAchievement
 * 
 * @method integer             getAchievementId()      Returns the current record's "achievement_id" value
 * @method string              getName()               Returns the current record's "name" value
 * @method string              getAchDescription()     Returns the current record's "ach_description" value
 * @method string              getAchImage()           Returns the current record's "ach_image" value
 * @method timestamp           getCreatedAt()          Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()          Returns the current record's "updated_at" value
 * @method Doctrine_Collection getStudentAchievement() Returns the current record's "StudentAchievement" collection
 * @method Achievements        setAchievementId()      Sets the current record's "achievement_id" value
 * @method Achievements        setName()               Sets the current record's "name" value
 * @method Achievements        setAchDescription()     Sets the current record's "ach_description" value
 * @method Achievements        setAchImage()           Sets the current record's "ach_image" value
 * @method Achievements        setCreatedAt()          Sets the current record's "created_at" value
 * @method Achievements        setUpdatedAt()          Sets the current record's "updated_at" value
 * @method Achievements        setStudentAchievement() Sets the current record's "StudentAchievement" collection
 * 
 * @package    ruckus_dev
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAchievements extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('achievements');
        $this->hasColumn('achievement_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('ach_description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ach_image', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('StudentAchievement', array(
             'local' => 'achievement_id',
             'foreign' => 'achievement_id'));
    }
}