<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BookSeries', 'doctrine');

/**
 * BaseBookSeries
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $series_id
 * @property string $name
 * @property string $series_icon
 * @property string $srs_description
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $Book
 * 
 * @method integer             getSeriesId()        Returns the current record's "series_id" value
 * @method string              getName()            Returns the current record's "name" value
 * @method string              getSeriesIcon()      Returns the current record's "series_icon" value
 * @method string              getSrsDescription()  Returns the current record's "srs_description" value
 * @method timestamp           getCreatedAt()       Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()       Returns the current record's "updated_at" value
 * @method Doctrine_Collection getBook()            Returns the current record's "Book" collection
 * @method BookSeries          setSeriesId()        Sets the current record's "series_id" value
 * @method BookSeries          setName()            Sets the current record's "name" value
 * @method BookSeries          setSeriesIcon()      Sets the current record's "series_icon" value
 * @method BookSeries          setSrsDescription()  Sets the current record's "srs_description" value
 * @method BookSeries          setCreatedAt()       Sets the current record's "created_at" value
 * @method BookSeries          setUpdatedAt()       Sets the current record's "updated_at" value
 * @method BookSeries          setBook()            Sets the current record's "Book" collection
 * 
 * @package    ruckus_dev
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBookSeries extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('book_series');
        $this->hasColumn('series_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('series_icon', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('srs_description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Book', array(
             'local' => 'series_id',
             'foreign' => 'series_id'));
    }
}