<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Faq', 'doctrine');

/**
 * BaseFaq
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $faq_id
 * @property string $faq_title
 * @property string $faq_description
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer   getFaqId()           Returns the current record's "faq_id" value
 * @method string    getFaqTitle()        Returns the current record's "faq_title" value
 * @method string    getFaqDescription()  Returns the current record's "faq_description" value
 * @method timestamp getCreatedAt()       Returns the current record's "created_at" value
 * @method timestamp getUpdatedAt()       Returns the current record's "updated_at" value
 * @method Faq       setFaqId()           Sets the current record's "faq_id" value
 * @method Faq       setFaqTitle()        Sets the current record's "faq_title" value
 * @method Faq       setFaqDescription()  Sets the current record's "faq_description" value
 * @method Faq       setCreatedAt()       Sets the current record's "created_at" value
 * @method Faq       setUpdatedAt()       Sets the current record's "updated_at" value
 * 
 * @package    ruckus_dev
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFaq extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('faq');
        $this->hasColumn('faq_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('faq_title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('faq_description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}