<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Avatar', 'doctrine');

/**
 * BaseAvatar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $avatar_id
 * @property string $name
 * @property string $avt_image
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer   getAvatarId()   Returns the current record's "avatar_id" value
 * @method string    getName()       Returns the current record's "name" value
 * @method string    getAvtImage()   Returns the current record's "avt_image" value
 * @method timestamp getCreatedAt()  Returns the current record's "created_at" value
 * @method timestamp getUpdatedAt()  Returns the current record's "updated_at" value
 * @method Avatar    setAvatarId()   Sets the current record's "avatar_id" value
 * @method Avatar    setName()       Sets the current record's "name" value
 * @method Avatar    setAvtImage()   Sets the current record's "avt_image" value
 * @method Avatar    setCreatedAt()  Sets the current record's "created_at" value
 * @method Avatar    setUpdatedAt()  Sets the current record's "updated_at" value
 * 
 * @package    ruckus_dev
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAvatar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('avatar');
        $this->hasColumn('avatar_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('avt_image', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}