<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('StudentAchievement', 'doctrine');

/**
 * BaseStudentAchievement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $student_achievement_id
 * @property integer $student_id
 * @property integer $achievement_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Achievements $Achievements
 * @property Students $Students
 * 
 * @method integer            getStudentAchievementId()   Returns the current record's "student_achievement_id" value
 * @method integer            getStudentId()              Returns the current record's "student_id" value
 * @method integer            getAchievementId()          Returns the current record's "achievement_id" value
 * @method timestamp          getCreatedAt()              Returns the current record's "created_at" value
 * @method timestamp          getUpdatedAt()              Returns the current record's "updated_at" value
 * @method Achievements       getAchievements()           Returns the current record's "Achievements" value
 * @method Students           getStudents()               Returns the current record's "Students" value
 * @method StudentAchievement setStudentAchievementId()   Sets the current record's "student_achievement_id" value
 * @method StudentAchievement setStudentId()              Sets the current record's "student_id" value
 * @method StudentAchievement setAchievementId()          Sets the current record's "achievement_id" value
 * @method StudentAchievement setCreatedAt()              Sets the current record's "created_at" value
 * @method StudentAchievement setUpdatedAt()              Sets the current record's "updated_at" value
 * @method StudentAchievement setAchievements()           Sets the current record's "Achievements" value
 * @method StudentAchievement setStudents()               Sets the current record's "Students" value
 * 
 * @package    ruckus_dev
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStudentAchievement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student_achievement');
        $this->hasColumn('student_achievement_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('student_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('achievement_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Achievements', array(
             'local' => 'achievement_id',
             'foreign' => 'achievement_id'));

        $this->hasOne('Students', array(
             'local' => 'student_id',
             'foreign' => 'student_id'));
    }
}