<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BookDetails', 'doctrine');

/**
 * BaseBookDetails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $book_detail_id
 * @property integer $book_id
 * @property string $bk_content_location
 * @property string $bk_price
 * @property string $bk_description
 * @property Book $Book
 * 
 * @method integer     getBookDetailId()        Returns the current record's "book_detail_id" value
 * @method integer     getBookId()              Returns the current record's "book_id" value
 * @method string      getBkContentLocation()   Returns the current record's "bk_content_location" value
 * @method string      getBkPrice()             Returns the current record's "bk_price" value
 * @method string      getBkDescription()       Returns the current record's "bk_description" value
 * @method Book        getBook()                Returns the current record's "Book" value
 * @method BookDetails setBookDetailId()        Sets the current record's "book_detail_id" value
 * @method BookDetails setBookId()              Sets the current record's "book_id" value
 * @method BookDetails setBkContentLocation()   Sets the current record's "bk_content_location" value
 * @method BookDetails setBkPrice()             Sets the current record's "bk_price" value
 * @method BookDetails setBkDescription()       Sets the current record's "bk_description" value
 * @method BookDetails setBook()                Sets the current record's "Book" value
 * 
 * @package    ruckus_dev
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBookDetails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('book_details');
        $this->hasColumn('book_detail_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('book_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('bk_content_location', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('bk_price', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('bk_description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Book', array(
             'local' => 'book_id',
             'foreign' => 'book_id'));
    }
}