<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BookLevels', 'doctrine');

/**
 * BaseBookLevels
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $level_id
 * @property string $level_code
 * @property string $name
 * @property string $level_description
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $Book
 * 
 * @method integer             getLevelId()           Returns the current record's "level_id" value
 * @method string              getLevelCode()         Returns the current record's "level_code" value
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getLevelDescription()  Returns the current record's "level_description" value
 * @method timestamp           getCreatedAt()         Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()         Returns the current record's "updated_at" value
 * @method Doctrine_Collection getBook()              Returns the current record's "Book" collection
 * @method BookLevels          setLevelId()           Sets the current record's "level_id" value
 * @method BookLevels          setLevelCode()         Sets the current record's "level_code" value
 * @method BookLevels          setName()              Sets the current record's "name" value
 * @method BookLevels          setLevelDescription()  Sets the current record's "level_description" value
 * @method BookLevels          setCreatedAt()         Sets the current record's "created_at" value
 * @method BookLevels          setUpdatedAt()         Sets the current record's "updated_at" value
 * @method BookLevels          setBook()              Sets the current record's "Book" collection
 * 
 * @package    ruckus_dev
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBookLevels extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('book_levels');
        $this->hasColumn('level_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('level_code', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('level_description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Book', array(
             'local' => 'level_id',
             'foreign' => 'level_id'));
    }
}