<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AssessmentActivity', 'doctrine');

/**
 * BaseAssessmentActivity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ass_act_id
 * @property integer $assessment_type_id
 * @property integer $activity_type_id
 * @property ActivityType $ActivityType
 * @property AssessmentType $AssessmentType
 * 
 * @method integer            getAssActId()           Returns the current record's "ass_act_id" value
 * @method integer            getAssessmentTypeId()   Returns the current record's "assessment_type_id" value
 * @method integer            getActivityTypeId()     Returns the current record's "activity_type_id" value
 * @method ActivityType       getActivityType()       Returns the current record's "ActivityType" value
 * @method AssessmentType     getAssessmentType()     Returns the current record's "AssessmentType" value
 * @method AssessmentActivity setAssActId()           Sets the current record's "ass_act_id" value
 * @method AssessmentActivity setAssessmentTypeId()   Sets the current record's "assessment_type_id" value
 * @method AssessmentActivity setActivityTypeId()     Sets the current record's "activity_type_id" value
 * @method AssessmentActivity setActivityType()       Sets the current record's "ActivityType" value
 * @method AssessmentActivity setAssessmentType()     Sets the current record's "AssessmentType" value
 * 
 * @package    ruckus_dev
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAssessmentActivity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('assessment_activity');
        $this->hasColumn('ass_act_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('assessment_type_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('activity_type_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ActivityType', array(
             'local' => 'activity_type_id',
             'foreign' => 'activity_type_id'));

        $this->hasOne('AssessmentType', array(
             'local' => 'assessment_type_id',
             'foreign' => 'assessment_type_id'));
    }
}