<?php

/**
 * AchievementsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AchievementsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AchievementsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Achievements');
    }
}