<?php

/**
 * ActivityParametersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityParametersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityParametersTable
     */
    
		static public $types = array(
			'integer' => 'integer',
			'float' => 'float',
			'varchar' => 'varchar',
		  );
	
		public static function getInstance(){
        
			return Doctrine_Core::getTable('ActivityParameters');
   
		}

		public function getTypes()
		  {
			return self::$types;
		  }
		
		public function func_getDataType($name, $activity_type_id){
		 $tbl_get_assessment_datatype = $this->createQuery('a')
			->where('a.name = ?',$name)
			->andWhere('a.activity_type_id = ?',$activity_type_id);
		 $tbl_result_assessment_datatype = $tbl_get_assessment_datatype->fetchArray();
		 return $tbl_result_assessment_datatype;
		}
}