<?php

/**
 * AssessmentTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssessmentTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssessmentTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssessmentType');
    }
}