<?php

/**
 * AvatarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AvatarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AvatarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Avatar');
    }
}