<?php

/**
 * BookLevelsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BookLevelsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BookLevelsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BookLevels');
    }
}