<?php

/**
 * BookDetailsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BookDetailsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BookDetailsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BookDetails');
    }
}