<?php

/**
 * BookSeries
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ruckus_dev
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BookSeries extends BaseBookSeries
{
	 public function save(Doctrine_Connection $conn = null)
      {
		$cls_commonfunction = new CommonFunctions();
		$path= $cls_commonfunction->basepath();
		
		
	    $file = $_FILES;
         if($file['book_series']['name']['series_icon']!=''){
            if(move_uploaded_file($file['book_series']['tmp_name']['series_icon'], $path."uploads/book_series/".time()."_".$file['book_series']['name']['series_icon'])){
               $this->setSeriesIcon(time()."_".$file['book_series']['name']['series_icon']);
            }
        }else{
		
			$this->getSeriesIcon("");
			
			}
        
      return parent::save($conn);
      }

}