<?php

/**
 * BookSeriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BookSeriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BookSeriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BookSeries');
    }
}