<?php

/**
 * GraphImagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GraphImagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GraphImagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GraphImages');
    }
}