<?php

/**
 * MetricResultVarcharTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MetricResultVarcharTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MetricResultVarcharTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MetricResultVarchar');
    }
}