<?php

/**
 * MetricResultIntegerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MetricResultIntegerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MetricResultIntegerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MetricResultInteger');
    }
}