<?php

/**
 * MetricParametersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MetricParametersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MetricParametersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MetricParameters');
    }
}