<?php

/**
 * MetricResultFloatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MetricResultFloatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MetricResultFloatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MetricResultFloat');
    }
}