<?php

/**
 * StudentAchievementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentAchievementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentAchievementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentAchievement');
    }
}