<?php

/**
 * TagsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TagsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tags');
    }
}