<?php

/**
 * TagTaxonomyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagTaxonomyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TagTaxonomyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TagTaxonomy');
    }
}